version: "3.8"

services:
  hku-vl-chat:
    container_name: hku-vl-chat
    image: hku-vl-chat:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_OLLAMA: "false"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped

    